version: "3.9"
services:
  postgresql:
    build:
      args:
        ALPINE_VERSION: "latest"
        CONTAINER_VERSION: "16.1"
        POSTGRES_MAJOR: "16"
        POSTGRES_MINOR: "1"
        POSTGRES_RELEASE: "r0"
      context: .
      dockerfile: container.build
      no_cache: true
      tags:
        - "postgresql:build"
        - "gautada/postgresql:build"
        - "gautada/postgresql:latest"
    image: "gautada/postgresql:latest"
    environment:
    - ABC=${XYZ}
    ports:
      - "5432:5432"
    volumes:
      - "Container:/mnt/volumes/container"
      - "Backup:/mnt/volumes/backup"
      - "Configmaps:/mnt/volumes/configmaps"
      - "Secrets:/mnt/volumes/secrets"

volumes:
  Container:
    external: true
    name: "Container"

  Backup:
    external: true
    name: "Backup"

  Configmaps:
    external: true
    name: "Configmaps"
    
  Secrets:
    external: true
    name: "Secrets"

