#!/bin/ash
#
# entrypoint: Located at `/etc/container/entrypoint` this script is the custom
#             entry for a container as called by `/usr/bin/container-entrypoint` set
#             in the upstream [alpine-container](https://github.com/gautada/alpine-container).
#             The default template is kept in
#             [gist](https://gist.github.com/gautada/f185700af585a50b3884ad10c2b02f98)

ENTRYPOINT_PARAMS="$@"
. /etc/profile

CONTAINER_NAME="postgres"
DB_DIR="/mnt/volumes/container/pgdata/cluster"
ARCHIVE_DIR="/mnt/volumes/container/pgdata/archive"

container_entrypoint() {
 if [ ! -d $DB_DIR ] ; then
  /bin/mkdir -p $ARCHIVE_DIR
  /usr/bin/initdb $DB_DIR
  unset $PGDATA
 fi
 
 mkdir /home/postgres/.tls
 /bin/cp /mnt/volumes/secrets/tls.key /home/postgres/.tls/tls.key
 /bin/cp /mnt/volumes/secrets/tls.crt /home/postgres/.tls/tls.crt
 /bin/chmod 0600 /home/postgres/.tls/tls.key
 /bin/chmod 0600 /home/postgres/.tls/tls.crt
 
 /usr/bin/postgres --config-file=/etc/container/postgresql.conf
 # -D $DB_DIR
}

container_version() {
 /usr/bin/postgres --version | awk -F ' ' '{print $3}'
}
