#!/bin/ash
#
# entrypoint: Located at `/etc/container/entrypoint` this script is the custom
#             entry for a container as called by `/usr/bin/container-entrypoint` set
#             in the upstream [alpine-container](https://github.com/gautada/alpine-container).
#             The default template is kept in
#             [gist](https://gist.github.com/gautada/f185700af585a50b3884ad10c2b02f98)

ENTRYPOINT_PARAMS="$@"
. /etc/profile

CONTAINER_NAME="postgres"
DB_DIR="/mnt/volumes/container/datastore"

if [ ! -d $DB_DIR ] ; then
 mkdir -p $DB_DIR
 /usr/bin/pg_ctl init --pgdata=$DB_DIR
 /bin/mv $DB_DIR/postgresql.conf $DB_DIR/postgresql.conf~
 /bin/mv $DB_DIR/pg_hba.conf $DB_DIR/pg_hba.conf~
 /bin/mv $DB_DIR/pg_ident.conf $DB_DIR/pg_ident.conf~
 /bin/ln -fsv /etc/container/pg_ident.conf $DB_DIR/pg_ident.conf
 /bin/ln -fsv /etc/container/pg_hba.conf $DB_DIR/pg_hba.conf
 /bin/ln -fsv /etc/container/postgresql.conf $DB_DIR/postgresql.conf
 unset $PGDATA
fi

container_version() {
 /usr/bin/postgres --version | awk -F ' ' '{print $3}'
}

start_db() {
 /usr/bin/pg_ctl start --pgdata=$1
}

start_app() {
 /usr/bin/pgweb --bind 0.0.0.0 --listen 8080 --host localhost --user $1
}

ep_launch() {
 FG="FG"
 BG="BG"
  
 TEST=$1
 APPLICATION=$2
 CONFIG=$3
 REDIRECT=$4
 
 # echo "$TEST $APPLICATION $CONFIG $REDIRECT"
  
 TYPE="$FG"
 if [ ! -z $REDIRECT ] ; then
  TYPE="$BG"
 fi
 log "-i" "entrypoint" "Testing - $TEST"
 /usr/bin/pgrep $TEST > /dev/null
 _T=$?
 if [ 1 -eq $_T ] ; then
  log "-i" "entrypoint" "$TYPE Launch - $APPLICATION"
  log "-i" "entrypoint" "--Config - $CONFIG"
  if [ "$TYPE" == "$BG" ] ; then
   log "-i" "entrypoint" "--Background - $REDIRECT"
   "$APPLICATION" "$CONFIG" > "$REDIRECT" 2>&1 &
   else
    "$APPLICATION" "$CONFIG"
   fi
 else
  log "-i" "entrypoint" "Test Failure - $TEST failed pgrep test"
 fi
}

entrypoint_launch() {
 PARAMS=$1
 TEST=$2
 APPLICATION=$3
 CONFIG=$4
 REDIRECT="/mnt/volumes/container/_log"

 log "-i" "entrypoint" "Container Launch - $CONTAINER_NAME[$(container_version)]"
 if [ -z "$PARAMS" ] ; then
  ep_launch "$TEST" "$APPLICATION" "$CONFIG"
  return 1
 else
  ep_launch "$TEST" "$APPLICATION" "$CONFIG" "$REDIRECT"
  return 0
 fi
}

ep_launch "postgres" "start_db" "$DB_DIR"
entrypoint_launch $@ "pgweb" "start_app" "postgres"
return $?
